version: "3"
services:
  nodeapp:
    image: nodeapp
    build: ./
    working_dir: /app
    environment:
      DB_HOST: mongodb://mongo:27017/posts
    ports:
      - 80:80
      - 3000:3000
    depends_on:
      - mongo
    command: bash -c "npm i && npm run start"
  mongo:
    image: mongo
    ports:
      - 27017:27017
